### ISSUE TITLE
PmagGui "Import all Replicates" does not work

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy-Standalone-OSX#3]
In trying to convert samples to MagIC format (step 1) the import all replicates function does not work on my student's computer.  Instead replicates are averaged.

**Comment by moonshoes87** [comment]
I'm sorry to find such an old issue here that doesn't seem to have been worked on.  @sslotznick, do you know if this problem is persistent?  If so, what specific import type is it failing with?

**Comment by sslotznick** [comment]
It occurred on a stand-alone version 3.0.1 (I think) when trying to import CIT format.  Unfortunately it was a summer student who has left so I don't know if it is persistent and we can't try to replicate the issue.  As I recall we ended up solely using the 2.0.1 version which did not have the issue.
