### ISSUE TITLE
clarity of instructions

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy-Standalone-OSX#4]
@Swanson-Hysell, the new instructions for downloading the standalone are actually wrong.  You actually have to go to the latest release and download there.  Since switching to pyinstaller, the standalone files are too big to track on Github (they cannot be uploaded by a git push).  Instead I just attach the zip file for each standalone to the release directly.  If you instead download from the repo, you will get something out of date.  

Obviously the old instructions weren't clear and need to be fixed.  @Swanson-Hysell, would you like to redo them, or do you want me to?   And maybe I will also delete the old standalones from the repo, so there is less room for confusion.

**Comment by moonshoes87** [comment]
@Swanson-Hysell, I updated it in a way that is hopefully more useful and clear.  Please let me know if this looks better to you!

**Comment by Swanson-Hysell** [comment]
Looks good. I made a few additional small edits.
