### ISSUE TITLE
Convert Error

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy-Standalone-OSX#7]
When converting CIT files to magic format, I tried to use the option 7 or 4 of the sample-site naming convention within PmagGui Standalone version 4.2.17.  When I try entering the number of X or Y i get a warning "naming convention option [X] must be in form 4-Z where Z is an integer."  (X is either 4 or 7 depending on which I am trying to do.)

I have tried older version and run into the same issue--potentially it is an issue with my data, but I thought I should report it.

**Comment by moonshoes87** [comment]
Thanks, @sslotznick.  I will try to have a look at this within the next week.

**Comment by moonshoes87** [comment]
I've fixed this on master: https://github.com/PmagPy/PmagPy/commit/167ff9343ae9fa1dc7a12735e4d7b0f516395663.  I will let you know as soon as I'm able to re-release the standalone (hopefully later this afternoon).  Thanks!

**Comment by moonshoes87** [comment]
@sslotznick, I just put up the new release: https://github.com/PmagPy/PmagPy-Standalone-OSX/releases/latest

Let me know if this doesn't work as you expect!

**Comment by sslotznick** [comment]
This works--thank you!
